name: Deploy to AWS

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set region "us-east-1"  # Change to your region

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Copy files to EC2
        env:
          EC2_USER: ubuntu
          EC2_IP: ${{ secrets.EC2_IP }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "starting deployment on $EC2_IP : $EC2_USER"
          echo "$SSH_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -o StrictHostKeyChecking=no -i private_key.pem -r . $EC2_USER@$EC2_IP:/home/$EC2_USER/project

      - name: Run deployment script
        env:
          EC2_USER: ubuntu
          EC2_IP: ${{ secrets.EC2_IP }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_IP 'bash ~/project/run.bash'

      - name: Clean up
        run: rm -f private_key.pem
